baseURL = "https://abhijitmohanty.com/"
languageCode = "en-us"
title = "Abhijit Mohanty"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  description = "Thoughts on software, systems, and building things."
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowShareButtons = false
  ShowWordCount = true
  disableSpecial1stPost = false
  mainSections = ["posts"]

  [params.label]
    text = "am"

  [params.author]
    name = "Abhijit Mohanty"
    email = ""

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/abhijitmohanty"

  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

[permalinks]
  posts = "/posts/:slug/"

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20

  [[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "/talks/"
    weight = 30

  [[menu.main]]
    identifier = "sponsors"
    name = "Sponsors"
    url = "/sponsors/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
